format: github

templates:
  header: |
    ---
    title: "{{.Name}}"
    linkTitle: "{{.Name}}"
    type: docs
    ---

output:
  - package: ./core/...
    path: docs-site/content/en/core.md
  - package: ./tbadk/...
    path: docs-site/content/en/tbadk.md
  - package: ./tbgenkit/...
    path: docs-site/content/en/tbgenkit.md