baseURL = "/"
title = "MCP Toolbox Go API Reference"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    title = "MCP Toolbox Go API Reference"
    languageName = "English"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  copyright = "Google LLC"
  privacy_policy = "https://policies.google.com/privacy"
  
  [params.ui]
    navbar_logo = true
    sidebar_menu_foldable = true
    sidebar_menu_compact = true

[module]
  [[module.imports]]
    path = "github.com/google/docsy"