baseURL = "https://anmolshukla2002.github.io/mcp-toolbox-sdk-go/"
title = "MCP Toolbox Go API"

[markup.goldmark.renderer]
  unsafe = true

[params.ui]
  navbar_logo = false
  sidebar_menu_foldable = true
  sidebar_search_disable = true
  breadcrumb_disable = true

[module]
  [[module.imports]]
    path = "github.com/google/docsy"