name: "API Reference Deployment"
on:
  push:
    branches: [ 'ref-docs' ]
    tags: [ 'v*' ]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.152.2'
          extended: true   
      
      - name: Install PostCSS Dependencies
        run: |
          cd docs-site
          npm install postcss postcss-cli autoprefixer

      - name: Build API Reference
        run: |
          chmod +x scripts/generate-api-docs.sh
          # Calculate Base URL
          if [[ "${{ github.repository }}" == "googleapis/mcp-toolbox-sdk-go" ]]; then
            BASE_URL="https://go.mcp-toolbox.dev/"
          else
            BASE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          fi
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=dev-$(git rev-parse --short HEAD)
          fi
          ./scripts/generate-api-docs.sh "$VERSION" "$BASE_URL"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site/public
          keep_files: true 
          cname: ${{ github.repository == 'googleapis/mcp-toolbox-sdk-go' && 'go.mcp-toolbox.dev' || '' }}
